config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'home#index'
  resources :links
  resources :posts, param: :static_page_name
  resources :subscribers, only: %i[new create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :link_type, optional: true
  belongs_to :user

  validates :display, inclusion: { in: [true, false] }
  validates :order, presence: true

  default_scope { order(order: :asc) }
  scope :visible, -> { where(display: true) }

  before_create :reorder_links_before_create
  before_destroy :reorder_links_before_destroy

  private

  def reorder_links_before_create
    ActiveRecord::Base.transaction do
      Link.find_each do |link|
        link.order += 1
        link.save
      end
    end
  end

  def reorder_links_before_destroy
    ActiveRecord::Base.transaction do
      Link.where(order: (order + 1)..).each do |link|
        link.order -= 1
        link.save
      end
    end
  end
end

app/models/link_type.rb
# frozen_string_literal: true

class LinkType < ApplicationRecord
  has_many :links, dependent: :nullify
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @links = user_signed_in? ? Link.all : Link.visible
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def edit
    @link = Link.find(params[:id])
  end

  def create
    @link = current_user.links.new(link_params)

    if @link.save
      redirect_to links_url
    else
      render :new
    end
  end

  def update
    @link = Link.find(params[:id])

    if @link.update(link_params)
      redirect_to link_url(@link)
    else
      render :edit
    end
  end

  def destroy
    link = Link.find(params[:id])
    link.destroy
    redirect_to links_url
  end

  private

  def link_params
    params.require(:link).permit(
      :display,
      :icon,
      :title,
      :url
    )
  end
end

app/helpers/links_helper.rb
# frozen_string_literal: true

module LinksHelper
end

app/views/links/_form.html.erb
<div>
  <%= form_with model: link do |form| %>
    <%= form.label :display %>
    <%= form.check_box :display %>
    <%= form.label :icon %>
    <%= form.text_field :icon %>
    <%= form.label :url %>
    <%= form.url_field :url %>
    <%= form.submit %>
  <% end %>
</div>

app/views/links/_link.html.erb
<div>
  <%= link_to link.url do %>
    <h1 class="font-bold text-4xl"><%= link.title %></h1>
    <% if user_signed_in? %>
      <p><%= link.display %></p>
    <% end %>
    <p><%= link.icon %></p>
    <p><%= link.url %></p>
    <%= link.order %>
  <% end %>
  <% if user_signed_in? %>
    <%= button_to 'Delete', link_path(link), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/links/edit.html.erb
<h1 class="font-bold text-4xl">Links#edit</h1>
<%= render partial: 'form', locals: { link: @link } %>

app/views/links/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Links#index</h1>
  <%= link_to 'Add Link', new_link_path %>
  <%= render @links %>
</div>

app/views/links/new.html.erb
<h1 class="font-bold text-4xl">Links#new</h1>
<%= render partial: 'form', locals: { link: @link } %>

app/views/links/show.html.erb
<%= render @link %>