config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'home#index'
  resources :links
  resources :posts, param: :static_page_name
  resources :subscribers, only: %i[new create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :posts_tags, dependent: :destroy
  has_many :tags, through: :posts_tags
  has_rich_text :body

  validates :deliver_newsletter, inclusion: { in: [true, false] }
  validates :static_page_name, presence: true, uniqueness: true
  validates :title, presence: true

  before_validation :create_static_page_name

  def to_param
    static_page_name
  end

  private

  def create_static_page_name
    self.static_page_name = title.parameterize unless title.nil?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @posts = Post.all
  end

  def show
    view_path = "/posts/static_pages/#{params[:static_page_name]}"

    if view_file_exist?(view_path)
      render view_path
    else
      redirect_to posts_url
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find_by(static_page_name: params[:static_page_name])
  end

  def create
    post = current_user.posts.new(post_params)

    if post.save
      StaticPageService.new(post).generate_static_page
      deliver_post_newsletter(post)
      redirect_to post_url(post)
    else
      render :new
    end
  end

  def update
    @post = Post.find_by(static_page_name: params[:static_page_name])
    old_static_page = StaticPageService.new(@post)

    if @post&.update(post_params)
      old_static_page.delete_static_page
      StaticPageService.new(@post).generate_static_page
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(static_page_name: params[:static_page_name])
    StaticPageService.new(@post).delete_static_page
    @post.destroy
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :body,
      :video_url,
      :deliver_newsletter
    )
  end

  def deliver_post_newsletter(post)
    return unless post.deliver_newsletter

    MailingList.post_newsletter_subscribers.find_each do |subscriber|
      PostMailer.with(post:, subscriber:).new_post.deliver_later
    end
  end

  def view_file_exist?(view_path)
    Rails.root.join("app/views#{view_path}.html.erb").exist?
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<div>
  <%= form_with model: post do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :video_url %>
    <%= form.url_field :video_url %>
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
    <% unless post&.created_at %>
      <%= form.label :deliver_newsletter, "Deliver in Newsletter" %>
      <%= form.check_box :deliver_newsletter, { checked: post&.deliver_newsletter.nil? || post.deliver_newsletter } %>
    <% end %>
    <%= form.submit %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div>
  <%= link_to post_path(post) do %>
    <h1 class="font-bold text-4xl"><%= post.title %></h1>
    <p><%= truncate(sanitize(post.body, tags: [])) %></p>
  <% end %>
  <% if user_signed_in? %>
    <%= button_to 'Post', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1 class="font-bold text-4xl">Posts#edit</h1>
<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Posts#index</h1>
  <%= link_to 'New Post', new_post_path %>
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<h1 class="font-bold text-4xl">Posts#new</h1>
<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/static_page.html.erb
<h1><%= post.title %></h1>
<p><%= post.body %></p>
<p><%= post.video_url %></p>
<p><%= post.user %></p>